apiVersion: v1
kind: Pod
metadata:
  name: app-dynamic
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: data
          mountPath: /var/data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc-dynamic
