apiVersion: v1
kind: Pod
metadata:
  name: demo-config-pod
spec:
  containers:
  - name: test-container
    image: nginx:alpine

    env:
    - name: APP_COLOR
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_COLOR

    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/app-secret"
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: app-secret
